/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2024-08-17 09:07:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class aboutus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>LMS - Laundry Management Service</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/laundry.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <section class=\"text-gray-600 body-font\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"max-w-6xl mx-auto p-4 md:p-16 xl:p-20 \">\r\n");
      out.write("            <div class=\"lg:w-2/3 space-y-5 text-center mx-auto\">\r\n");
      out.write("              <h1 class=\"text-gray-800 uppercase tracking-widest font-medium text-4xl\">\r\n");
      out.write("                About Us\r\n");
      out.write("              </h1>\r\n");
      out.write("              <div class=\"h-0.5 bg-green-400 w-14 mx-auto\"></div>\r\n");
      out.write("              <p class=\"text-gray-500 text-base leading-6\">\r\n");
      out.write("                Welcome to CleanWave Laundry Solutions, where cleanliness meets convenience. Founded in 2015, CleanWave started with a simple goal: to make laundry services easy, efficient, and affordable for everyone. Over the years, we’ve grown from a small local service to a leading laundry management provider, serving thousands of customers every day.\r\n");
      out.write("              </p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container flex flex-wrap px-5 py-24 mx-auto\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"flex flex-wrap -mx-4 mt-auto mb-auto lg:w-1/2 sm:w-full content-start sm:pr-10\">\r\n");
      out.write("            <div class=\"w-full sm:p-4 px-4 mb-6\">\r\n");
      out.write("              <h1 class=\"title-font font-medium text-3xl mb-2 text-gray-900\">Our Mission</h1>\r\n");
      out.write("              <div class=\"text-gray-500 leading-relaxed\">At CleanWave, our mission is to redefine the laundry experience by offering top-notch services with a commitment to quality, reliability, and sustainability. We believe that doing laundry shouldn’t be a chore, and our goal is to make it as seamless as possible for our customers.</div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"p-4 sm:w-1/2 lg:w-1/4 w-1/2\">\r\n");
      out.write("              <h2 class=\"title-font font-medium text-3xl text-gray-900\">1.7K</h2>\r\n");
      out.write("              <p class=\"leading-relaxed\">Customers</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"p-4 sm:w-1/2 lg:w-1/4 w-1/2\">\r\n");
      out.write("              <h2 class=\"title-font font-medium text-3xl text-gray-900\">8.8K</h2>\r\n");
      out.write("              <p class=\"leading-relaxed\">Subscribes</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"p-4 sm:w-1/2 lg:w-1/4 w-1/2\">\r\n");
      out.write("              <h2 class=\"title-font font-medium text-3xl text-gray-900\">3</h2>\r\n");
      out.write("              <p class=\"leading-relaxed\">Awards</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"p-4 sm:w-1/2 lg:w-1/4 w-1/2\">\r\n");
      out.write("              <h2 class=\"title-font font-medium text-3xl text-gray-900\">4</h2>\r\n");
      out.write("              <p class=\"leading-relaxed\">Branches</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"lg:w-1/2 sm:w-1/2 md:w-1/2 w-auto rounded-lg overflow-hidden mt-6 sm:mt-0\">\r\n");
      out.write("            <img class=\"object-cover object-center w-full h-full\" src=\"./Resources/wahsing-machine-image.jpg\" alt=\"stats\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"w-full sm:p-4 px-4 mb-6\">\r\n");
      out.write("            <h1 class=\"title-font font-medium text-3xl mb-2 text-gray-900 text-center\">Join us on our journey</h1>\r\n");
      out.write("            <div class=\"text-gray-500 leading-relaxed text-justify\">We are more than just a laundry service; we are a community that values cleanliness, sustainability, and customer satisfaction. Join us on our journey as we continue to innovate and elevate the laundry experience for all.</div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </section>\r\n");
      out.write("\r\n");
      out.write("              <!--footer-->\r\n");
      out.write("              <div class=\"bg-[#70008C] text-white max-w-l py-4 mb-0\">\r\n");
      out.write("              <div class=\"container mx-auto px-4 sm:px-6 lg:px-8\">\r\n");
      out.write("                   <div class=\"flex flex-col sm:flex-row justify-between items-center\">\r\n");
      out.write("                      <div class=\"text-center sm:text-left mb-2 sm:mb-0\">\r\n");
      out.write("                          © 2024 Laundry Management Service. All rights reserved.\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"text-center sm:text-right\">\r\n");
      out.write("                          12 Laundry St, Clean City, CS 45678\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
